import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  style={{backgroundColor:"rgb(156, 236, 241)"}} className={inter.className}>{children}</body>
    </html>
  )
}
// import { useRouter } from 'next/router';
// import 'bootstrap/dist/css/bootstrap.css';
// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   const router = useRouter();
//   const isAdminDashboard = router.pathname.startsWith('/admin');

//   return (
//     <html lang="en">
//       <body 
//         style={{backgroundColor: isAdminDashboard ? '' : 'rgb(156, 236, 241)' }} 
//         className={inter.className}>{children}
//       </body>
//     </html>
//   )
// }